### ISSUE TITLE
[Suggestion] Advanced exmple

### ISSUE THREAD

**Issue by FeelsBadMan1** [PythonistaGuild/Wavelink#101]
Hello,
Wavelink is working good but in my opinion there a a few missing things:

- loop song & queue
- lyrics command
- pitch (1.00 standard 5.00 max)
- option to keep the bot into the voicechannel even if nothing is playing.

**Comment by Cafeepy** [comment]
Hi there, 

I'm glad to hear that Wavelink is working for you. However, loops and queues aren't a part of Wavelink because it's relatively simple to implement that yourself. After all, the example is just an example and you're free to write your own code instead.

Lavalink itself is unable to provide lyrics, so there's not really a reason why Wavelink would have a lyrics command. For lyrics, maybe try taking a look at [KSoft.Si](https://api.ksoft.si), as they're the leading provider of lyrics for Discord bots. 

I'm not sure about pitch and what you mean by the last two points, so maybe someone with more Wavelink expertise than me would be able to answer those. Hope this helped, have a nice day!

**Comment by FeelsBadMan1** [comment]
Oh thanks you for the Information. I will take a look on KSoft and try to create my own loop command. However is Kisoft possible to implement in wavelink?

**Comment by FeelsBadMan1** [comment]
I cant create a new Application on KSoft.Si during following popup:
![image](https://user-images.githubusercontent.com/40109798/119224520-0fd55c80-baff-11eb-9aff-df41e2d2b67b.png)

**Comment by Cafeepy** [comment]
Hi there, 

No, KSoft.Si is not part of Wavelink, but they do have an [official Python API wrapper](https://github.com/KSoft-Si/ksoftapi.py) you can look into. And yes, unfortunately KSoft.Si has had a lot of applications lately so they aren't accepting new ones until they sort things out on their end, unless you have an extraordinary project that needs immediate attention, in which case you can email them. You can also join both Wavelink and KSoft.Si's Discord servers to ask for more help on each of those topics respectively. Hope this helped!
