### ISSUE TITLE
player "connects" to locked channel at max capicaity

### ISSUE THREAD

**Issue by Redhawk18** [PythonistaGuild/Wavelink#204]
version: 1.3.3

replicate:
1. create a locked voice channel with a capacity of 1
2. bot must not have admin perms
3. do whatever play command to have it join a voice  channel

problem:
* Bot does not join the voice channel, but acts like it does with events. For example a `on_wavelink_track_start` is sent, but `on_wavelink_track_end` isn't trigger until the track "ends". 
* When the `on_wavelink_track_start` should never be sent or, the `on_wavelink_track_end` should trigger instantly.

**Comment by cloudwithax** [comment]
This isnt something to do with Wavelink but within Discord itself (its actually a feature). Discord allows certain users with perms (bots dont need them though) to connect to voice channels with a limit, effectively ignoring it. In this case, the bot is actually connected to the channel and sending data, but since the channel has a limit (and the bot is not aware of that limit), it'll join anyway and send data like it normally would whilst not being visible to you at all. To remedy this, check if the channel you're connecting to first has a limit and that joining wont put you over the limit and disallow it from connecting if those criteria apply.

**Comment by Redhawk18** [comment]
> This isnt something to do with Wavelink but within Discord itself (its actually a feature). Discord allows certain users with perms (bots dont need them though) to connect to voice channels with a limit, effectively ignoring it. In this case, the bot is actually connected to the channel and sending data, but since the channel has a limit (and the bot is not aware of that limit), it'll join anyway and send data like it normally would whilst not being visible to you at all. To remedy this, check if the channel you're connecting to first has a limit and that joining wont put you over the limit and disallow it from connecting if those criteria apply.

do you mean discord or discord.py? Because this seems like a really bad choice.

**Comment by cloudwithax** [comment]
Its Discord, not discord.py. If you have qualms with that functionality, bring it up with them.
