### ISSUE TITLE
iterator method does not work on spotify albums

### ISSUE THREAD

**Issue by Wicardorith** [PythonistaGuild/Wavelink#209]
![image](https://user-images.githubusercontent.com/46023690/227718991-06e6c5f3-7ab6-4afc-8390-a835e5ee7fad.png)

I tried using "spotify.SpotifySearchType.playlist" for the "type" parameter. It does not work either.

It works for playlists, but does not work if any album is given. 
It was working just fine on the previous release (1.3.5).

OS: Ubuntu 22.04.2
Wavelink: 2.0.3
Lavalink: 3.7.5

**Comment by andrewyazura** [comment]
I'm experiencing the same issue currently, it only happens when providing a Spotify album URL. The error's traceback:

```python
Traceback (most recent call last):
  ...
  File "/usr/local/lib/python3.11/site-packages/wavelink/ext/spotify/__init__.py", line 156, in __anext__
    track = SpotifyTrack(track)
            ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wavelink/ext/spotify/__init__.py", line 227, in __init__
    self.isrc: str | None = data["external_ids"].get("isrc")
                            ~~~~^^^^^^^^^^^^^^^^
KeyError: 'external_ids'
```

It looks like the Spotify API only returns `external_ids` property when requesting individual tracks or playlists, but not for albums: [get album method](https://developer.spotify.com/documentation/web-api/reference/get-an-album).

[get tracks method](https://developer.spotify.com/documentation/web-api/reference/get-track):
```json
...
  "external_ids": {
    "isrc": "string",
    "ean": "string",
    "upc": "string"
  },
...
```

[get playlist method](https://developer.spotify.com/documentation/web-api/reference/get-playlist):
```json
...
    "items": [
       {
          "external_ids": {
            "isrc": "string",
            "ean": "string",
            "upc": "string"
          },
       }
    ]
...
```

**Comment by EvieePy** [comment]
See: #222
