### ISSUE TITLE
Extra xxx characters when host is not an IP

### ISSUE THREAD

**Issue by F4stZ4p** [PythonistaGuild/Wavelink#21]
**Right now, when wavelink hides your IP in logs, it looks like this:**
```python
WAVELINK:WEBSOCKET | Connection established::MAIN - (radiowo-ll.herokuapp.xxx.xxx:80) | europe | (Shard: None)
```
**Expected:**
```python
WAVELINK:WEBSOCKET | Connection established::MAIN - (radiowo-ll.herokuapp.xxx:80) | europe | (Shard: None)
```

Host is `radiowo-ll.herokuapp.com`

**Comment by gamescom15** [comment]
Maybe the whole parsing and censoring of the Hostname/IP should be thought through again.

Censoring the `.com` to `.xxx` does not really anonymize anything at all, it's much more likely you'd want to hide either the domain name or the subdomain instead of (or in addition to) the tld.

Given an arbitrary hostname, it's near impossible for the library to automatically decide which parts to censor, as it could be the hostname itself, the subdomain or in case of an IP the last 2 octets.

Implementation idea 1:
censor the last 2 parts (`.split('.')`, then `[:-2]`)
`radiowo-ll.herokuapp.com` -> `radiowo-ll.xxx.xxx` 
* `+` gives the owner the necessary information (as in which cname it refers to -> `radiowo-ll`)
* `+` hides the fact that you're hosting on heroku
* `-` if they know you're hosting on heroku, the censoring is pointless

`203.0.113.1` -> `203.0.xxx.xxx`
* `+` censors the IP properly
* `+` looks the same as the current solution -> no visual changes for IPs

When reimplementing this, #15 / #17 would also need to be considered.

**Comment by EvieePy** [comment]
Fixed as host was removed from repr. Thanks
