### ISSUE TITLE
Autoplay doesn't triggers the on_wavelink_track_start event.

### ISSUE THREAD

**Issue by Saur-av** [PythonistaGuild/Wavelink#295]
When a Track starts while the AutoPlay is enabled, the on_wavelink_track_start isn't being triggered when a new track is started by the autoplay.

**Comment by EvieePy** [comment]
Can you provide more details, like `code`, `wavelink version`, `Lavalink version` and any relevant logs?

The most common cause of this problem is people using the `on_wavelink_track_end` event in an incompatible way with `AutoPlay`. If you use `AutoPlay` we strongly recommend not doing any logic in that event.

You can avoid issues by returning early, for example:

```py
@commands.Cog.listener()
async def on_wavelink_track_end(self, payload: wavelink.TrackEndEventPayload) -> None:
    player = payload.player
    
    if not player or player.autoplay is not wavelink.AutoPlayMode.disabled:
        return
        
    # If you get here, you aren't using AutoPlay...
    ...
```

**Comment by Saur-av** [comment]
Thanks for the help, I went through my code again and I noticed that I was getting rate limits as per what I wanted to achieve after  the `on_wavelink_track_end` is invoked.
